### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by MoWangDaRen** [MambaLLIE/MambaLLIE#1]
There is a problem when i try to run train.py. I try to substitude root_path with absolute path of the home directory. but there is the same problem.

**Comment by MoWangDaRen** [comment]
Disable distributed.
Traceback (most recent call last):
  File "basicsr/train.py", line 225, in &lt;module&gt;
    train_pipeline(root_path)
  File "basicsr/train.py", line 101, in train_pipeline
    opt, args = parse_options(root_path, is_train=True)
  File "/home/sca-345/miniconda3/envs/mamballie/lib/python3.8/site-packages/basicsr/utils/options.py", line 148, in parse_options
    dataset['dataroot_gt'] = osp.expanduser(dataset['dataroot_gt'])
  File "/home/sca-345/miniconda3/envs/mamballie/lib/python3.8/posixpath.py", line 231, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not list

**Comment by MambaLLIE** [comment]
Thanks for your issue. You may need to modify the contents of the YML file under the options. This also reminds us to provide a detailed guide for training and testing. We will work on completing these details as soon as possible.
